$(function(){
			$(".about2").hover(function(){
			$(".nav-2").show();
		},function(){
			$(".nav-2").hide();
		});
			$('.nav-2').hover(function(){
				$(this).show()
			},function(){
				$(this).hide()
			})
		 $(".about").hover(function(){
			$(".nav-1").show();
		},function(){
			$(".nav-1").hide();
		});
			$('.nav-1').hover(function(){
				$(this).show()
			},function(){
				$(this).hide()
			})
			
})